### ISSUE TITLE
Implement turbo loader features for GBA

### ISSUE THREAD

**Issue by mathieulh** [MiSTer-devel/Main_MiSTer#168]
This is not a bug, this is an enhancement request:

ROM loading on large GBA roms is exceptionally slow (especially compared to flashcarts containing PSRAM on real hardware, we are talking of a 10:1 ratio at the very least), I noticed a faster "turbo" loader implemented for the Neo Geo core and I was wondering if the same couldn't be done for future GBA fast loading support.

To be specific it takes about 25 seconds on average to load a 32MB rom (versus instant on real hardware).

I am well aware that there are limitations/constraints as to doing this as this would have you maintain another specific loader in the main code, therefore I can understand if you do not wish to implement this, this is mostly a pending ehancement request for review.

**Comment by sorgelig** [comment]
Fast loading in NeoGeo is done by loading the file into DDR3 memory instead of sending it through communicating pipe to FPGA. Because NeoGeo has special multi-file ROM structure it has a special loader which incorporates turbo loading.
GBA has option to use DDR3, so probably i can implement some generic loader to DDR3 if core request it. So at least DDR3 mode can use turbo loader. But GBA needs to scan the whole ROM to get some required info before start it. It will require additional work from FPGA side since the data won't go through communicating pipe.
May be, at some point GBA will get such loader. 
Anyway, it's GBA specific "issue", not the Main. So i close it.
