### ISSUE TITLE
NEW FEATURE: Core config pre/post processing in readable format.

### ISSUE THREAD

**Issue by theypsilon** [MiSTer-devel/Main_MiSTer#207]
Right now the `.cfg` files in `config/` folder are binaries that are directly sent/received to/from the core, if I'm not mistaken.

This is fast, but as a binary file is not very easy to read with external tools. And more importantly, doesn't contain index data other than the bit position in the file.

It also means that a developer need to be conservative when adding/removing options in a core. Since needs to avoid possible collisions in the status bitmap after those changes, and it's not that flexible.

My proposal would be to translate the bitmaps into a readable file, like `.ini` . And then save/load from it, by doing a translation from string to bit representation. This would allow not only human modificaion of the configs by hand, but also would allow scripts to change some settings in many cores at once. And the other added benefit, as I commented before, would be the more flexibility when adding/removing options from a core. Old `.cfg` would have to be still supported for backwards compatibility but the new saves would be done in the new readable format.

Of course, it comes with the known important drawbacks. Speed impact in core config loading/saving. And more code to mantain, specially the one where you would encode the readable <=> bitmap representation in MiSTer_Main to keep it synced with the status bitmap in the core. That means, more coupling between main and the cores.

If you think this is worth expending some time, I'd be working for providing you a working branch with a spike of this feature. And in case this is decided to be adopted, I'd be up for implementing it and mantaining it for as many cores as possible.

**Comment by sorgelig** [comment]
As the main dev who ported may be 90%+ cores with often big refactoring i can say this problem is non-existent.
Absolutely not a problem.  Current way it implemented is very convenient. Also, there is a quick way to reset to 0 for the whole config if you are not sure which values are default.

You need to understand, some features are designed one way and not expecting to work another way. For example OSD settings for core are designed the way when user change it from OSD only. It doesn't expect that user will change in manually in config file. 
Treat it as storage, not user serviceable.

**Comment by theypsilon** [comment]
Cool, thanks for expending your time in explaining your reasoning. Btw, I didn't want to portrait this as there was a problem. That wasn't the point. I hope I could have make that more clear. I'm closing it then.
