### ISSUE TITLE
Direct Video: Green is over-attenuated when YPbPr is enabled

### ISSUE THREAD

**Issue by Em-K-IronFist** [MiSTer-devel/Main_MiSTer#210]
I've been testing Direct Video mode with a lot of different configurations. I have tried three different HDMI-to-VGA DACs, I've used sync-on-green and also tried a separate sync line (4 BNC connectors, RGB + Sync) on my PVM, and while RGB looks flawless, YPbPr does not appear to be displaying correctly. It has a strong pink tint on all the cables and DACs I have tested. Keep in mind: these same cables work perfectly for RGB, even when using Sync-on-Green (with a cable containing the correct circuit), so I am fairly confident the cables are not to blame.

I have also gotten the Moread DAC recommended by the community; it performs about the same as the other two DACs I tested; all three do just fine with RGB but output signals with a pink tint in YPbPr mode. I have also tried `hdmi_limited=0`,  `hdmi_limited=1` and `hdmi_limited=2` just to make sure that it wasn't a color range issue.

Looking at the test patterns in 240p test suite, the green signal is still there but it is very low. I played with my signal using some attenuators and I noticed the pink tint went away if I attenuated red and blue to bring them into "balance" with green, however this kills the saturation of the image.

I have not been able to find any other examples of people using Direct Video with YPbPr connections, so it is hard for me to know if this is an issue that affects multiple users or if I am simply unlucky.

**Comment by sorgelig** [comment]
YPbPr doesn't work well on all TVs. It's actually kind of hack, as HDMI-VGA converters aren't designed for YPbPr. Some TVs/Monitors sense the gain of green too early in blanking area, before MiSTer can provide reference Y level. So these displays aren't compatible with YPbPr from HDMI-VGA converter. Better to use some dummy RGB->YPbPr converter if you have such.
But since your TV supports RGB, i suggest to use RGB - this is native to MiSTer color space.

**Comment by Em-K-IronFist** [comment]
Thank you for this information, this has been very helpful. Will close this issue now and update the wiki with additional information. :)
