### ISSUE TITLE
Pass mouse scroll wheel data to Minimig core

### ISSUE THREAD

**Issue by apolkosnik** [MiSTer-devel/Main_MiSTer#248]
Would it be possible to feed the scroll wheel data to the Minimig core?
Thanks!

**Comment by c0d3h4x0r** [comment]
+1, I would really like to see this working as well.  My AmigaOS 3.1.4 `.hdf` image is definitely set up with all the correct libraries and commodities to make this work, because mouse wheel scrolling works using that same exact `.hdf` on both a Raspberry Pi 3b+ running Amiberry and a Windows 10 PC running WinUAE.  So this must be something simply not implemented on the Linux input side, or maybe not implemented by the core itself, or both.

**Comment by apolkosnik** [comment]
The latest updates to Main and Minimig make the scroll wheel work with FreeWheel app. Good stuff. I'll close the issue. Thanks!
