### ISSUE TITLE
Proposal: Maintain release and version history in Github.

### ISSUE THREAD

**Issue by coughlanio** [MiSTer-devel/Main_MiSTer#3]
Just want to leave my two cents here, but you/we should consider tagging releases and attaching binaries as supported by github. This will make maintaining the version history a lot more transparent.

**Comment by sorgelig** [comment]
It won't be more transparent because every core has its own repository. Currently I'm using the forum's dedicated topic as centralized announce about releases. It's more convenient for user to track the changes.

Probably, separate Wii page can be used for the same purpose, but i think the forum is better since it assume discussions.

Anyway, i will see what can i do for releases. Since i'm the only who currently write the code, the current way is more convenient for me.

**Comment by coughlanio** [comment]
While the forum might be more convenient for end users to see a concise change log, I think there's value from a developer perspective to have clearly defined tags, releases and binaries, and to maintain a separation between source code and compiled artifacts.

I understand the convenience from your perspective, to do what works for you, but adhering to Github conventions, and standardizing a release process will be more inviting to other developers (like myself).

**Comment by sorgelig** [comment]
I think it's more correct way to start to develop for MiSTer first and then if you will see some real difficulties then talk to me - i'm ready to listen how to improve it. As long as i'm the only significant developer for MiSTer, i will organize it in the way convenient for me.
I think, the whole MiSTer project organization is already much more convenient than most other similar projects.
Usually each core has its own dedicated developer and its repository organization doesn't affect other cores where it can be organized differently.

**Comment by jcw** [comment]
The current setup works fine for me. Whatever makes life easiest for @sorgelig matters most IMNSHO, since he's been doing all the work (I'm hoping to bump my FPGA-fu one day, to be able to participate a bit more). My suggestion, if you want to contribute (hurray, please do!), is to go with the flow first. Changes in process can always be made at a later date.

Only suggestion I'd like to add is that perhaps a more prominent link to the Atari MiSTer forum might help, at least for those who are more GitHub-centric, like me...

**Comment by sorgelig** [comment]
i've added link on wiki's side panel. That should be visible enough

**Comment by Quantum-cross** [comment]
I was going to post an issue for this. I really wish releases and binaries were tagged using github's releases tab.

- Releases on all cores aren't in release order, I and many other people have accidentally grabbed minimig releases from a year ago because they're in random order.

- Instead of this weird bootstrap thing written in golang, if releases were tagged you could just `wget` `.../releases/latest` for every core, making updating and linking to the latest version of cores trivial and clean.
