### ISSUE TITLE
Please change repo name

### ISSUE THREAD

**Issue by blm397** [MiSTer-devel/Main_MiSTer#304]
The word "mister" is a derivation of the word "master" (see: https://www.grammarphobia.com/blog/2017/05/mister.html). In light of recent patch to Git removing master as a default branch, it seems appropriate to remove other derivations that cause hurtful imagery and harm inclusivity. Thanks for understanding.

**Comment by sacredbanana** [comment]
I doubt you'd be able to find anyone else being offended by the MiSTer name. I love the name

**Comment by 172pilot** [comment]
Looks like the BLM397 account joined GIT today simply to make this complaint.  Somehow my time is never best spent going around looking for ways to be offended..  I just dont get it

**Comment by sacredbanana** [comment]
I hope it's not offensive when someone introduces himself as Mr <insert surname here>

**Comment by rikard-softgear** [comment]
What a joke.

**Comment by Vampier** [comment]
I had an idea - but replacing the I with an A will make it even more offensive. I don't think an arbitrary link to a website that is occupied with looking for an 'word' offense is credible. I support BLM I do not' support blm397's notion as it seems to be malicious in nature. Looking at the MiSTer name and history MiST-MiSTer it doesn't even have anything to do with the word 'mister'. I also don't understand what's so offensive about misters anyway, even Amazon sells them. 

https://www.amazon.com/Sustainable-Village-WA16146-Brass-Mister/dp/B01FCFECWY

**Comment by xolod79** [comment]
1984 freedom is slavery

**Comment by kblood** [comment]
Created a GIT account, called BLM, only to make an issue like this... that is pretty funny :)

It has been brought up in other IT related issues before... like hard drives and such being set to "master" and "slave" but has also been brought up in regards to GIT and similar that have a "master" branch... where ti just seems less relevant since there is no slave equivalent.

Words are words. No need to put more meaning into them than they have.
