### ISSUE TITLE
Bind 3x buttons to a single joypad button

### ISSUE THREAD

**Issue by buvk** [MiSTer-devel/Main_MiSTer#427]
I was just curious whether it would be possible to implement a feature where you can bind 3x buttons to a single joypad button.  This would be useful for pad users in games such as ssf2t.

Thanks!

**Comment by sorgelig** [comment]
I'm not fully get what you want to achieve.
It seems you are using inconvenient or not compatible gamepad which usually can be fixed by replacing the gamepad.

**Comment by buvk** [comment]
I use an 8BitDo M30 and a Sega Saturn controller (both of which have 6 face buttons).  I would like to make it so that pressing left trigger is equivalent of pressing the 3 top face buttons (light punch, medium punch, heavy punch), and pressing right trigger is equivalent of pressing the 3 bottom face buttons (light kick, medium kick, heavy kick).

A stick would probably be more convenient vs. a pad for fighting games like Street Fighter when executing 3P (triple punch) and 3K (triple kick) moves, however, I do not have a stick, and personally do prefer to play on a pad.

**Comment by paulb-nl** [comment]
I think this should be handled in the core. Jotego can add 3xP and 3xK buttons to the MRAs.

**Comment by buvk** [comment]
jotego mentioned this could be better done by the firmware layer.

https://github.com/jotego/jtcps1/issues/104

**Comment by paulb-nl** [comment]
Yea probably to save him work lol. 

I think this would be difficult to add to MiSTer main while it is relatively easy in the core. 

How would we choose in the MiSTer OSD which buttons to bind to another button?

**Comment by sorgelig** [comment]
It's a matter of proper controller. Fighting arcade games are expecting a large stationary controller, not small gamepad. So it should be played on such controller. There you will be able to use three fingers at the same time. 
Otherwise it's core's task to add additional button. Arcade core should know which buttons should be merged while MiSTer framework doesn't.

**Comment by boogermann** [comment]
Not really a matter of proper controller but actually a feature commonly found on Arcade ports for consoles with more then 6 buttons.
For instance on Capcom games, some moves requires pressing 2 or 3 buttons at the same time to activate a special movement.
On the playstation for example you could map L2 to act as if Square, Triangle and L1 were pressed at the same time, basically a combo/macro key. That was usually set in the game joystick mapping with pre-defined combos.
The core/framework doesn't really need to know these combo keys as the firmware could easily provide by expanding the mapping feature, the same way we can map say start+select to act as the menu key it could be done to set a combination of key to be mapped to extra keys.
That would also require to change the virtual gamepad to actually have 8 buttons instead of 6, so after mapping L and R you could map combo keys to L2 and R2 on a Playstation controller or L/R on the Saturn for example.

**Comment by sorgelig** [comment]
It should be core specific implemented as an additional key. Similar to ABC key on NeoGeo. It's performance cost-free implementation unlike additional processing on HPS side. Also only few cores really need it.

**Comment by buvk** [comment]
@jotego what are your thoughts on this?

**Comment by jotego** [comment]
I think the firmware is a better place for this than the cores. 
For instance, suppose you have a single RBF file that gives support for some 30 games -not counting alternative ones. From these 30, mapping some button combinations to a single button will not apply to all games. And it will depend upon user preference. The core will have to be defined as recognizing more inputs than the original hardware did too, making it less portable. 
I think it is better to tackle this problem from the firmware side. It can be done there in a general way that is transparent to the actual cores. Making it a firmware feature automatically enhances all systems, adding value to the platform as a whole.

**Comment by sorgelig** [comment]
This task is specific to core, so it should be done per-core. 
Example is in NeoGeo core.
