### ISSUE TITLE
Feature Request : Global 90/270 Screen Rotation

### ISSUE THREAD

**Issue by rgavril** [MiSTer-devel/Main_MiSTer#478]
An ini option to rotate the screen (game output and osd) 90/270 degrees would be very useful in at least two scenarios:

- Since large 4:3 or 1:1 displays are hard to find, when constructing a custom arcade cabinet a good alternative is to use a standard 16:9 screen in vertical orientation and show a 1:1 area (for hdtv 1080x1080). This will act as a great display for both horizontal and vertical games. Currently not possible with mister as there is no option to flip horizontal games and show them on a vertical orientated screen.

- People that use an lcd with rotating stand, as it would mean just switching to an alternate ini file when rotating the monitor with no need to configure each core individually. This could even be automated with script if the option exists.

**Comment by sorgelig** [comment]
OSD rotation is already implemented.
Video rotation is implemented in arcade cores. For other cores it's practically impossible due to large demanded resources and memory bandwidth.
MiSTer is primarily targeted for TV output which is normal horizontal position.

I can give you a hint for large display. Use video projector from the back. So you can project it to a matte glass with basically any aspect ratio you want. Today you can find many mini-projectors with FHD resolution.

**Comment by rgavril** [comment]
Was imagining that, since vertical cores can be rotated it is possible to do the same for horizontal cores, after all vertical or horizontal game is just a human made classification.

As you figure out I’m interested in playing arcade cores on this setup.

I noticed that CPS 1/2 core does support screen rotation (at least vertical games) and to my knowledge is quite demanding from the resources point of view. 

But think I got your point, is not possible to do it in Main as a global option, each core needs to implement it, which is a pain :(

**Comment by jotego** [comment]
The CPS core supports screen rotation. If you start a vertical game, the option will appear in the OSD. Otherwise, the option is not shown.
If you are referring to screen flip, then you just have to go into the DIP settings of each game to enable the flip mode. In CPS2 DIP settings are in the service menu, into which you enter by either pressing F2 or by selecting the test OSD item.

**Comment by rgavril** [comment]
Thanks @jotego the issue is not about vertical games, I would like to use rotation for horizontal games too.

My target is to use a 16:9 display in vertical position inside my custom arcade cabinet. By covering the top/bottom parts of the screen with the cabinet (behind control panel and marquee) I would end up with a square aspect ratio screen in which I can display any vertical or horizontal game.

For example: A 43'' 16:9 display can be used as an 29.8'' 1:1 display. That will translate to a virtual 26.3'' display for 4:3 and 3:4 games.

![sidelayout](https://user-images.githubusercontent.com/5073422/143402863-c17e7dba-7500-4c5c-a026-705cf172b923.png)

**Comment by jotego** [comment]
Indeed, for such a case we would need a global setting. If the OSD rotation setting (in the mister.ini file) was readable from the core, then the core could adapt to this by always showing the rotate OSD option.

**Comment by sorgelig** [comment]
I'm closing this issue as it's not possible to rotate the screen in ALL cores.
