### ISSUE TITLE
Scanlines intensity modulation / hybrid scanlines

### ISSUE THREAD

**Issue by darkworon** [MiSTer-devel/Main_MiSTer#510]
RetroTink and Analogue have something called hybrid scanlines (or scanlines intensity modulation) which changing the width of the line based on the brightness of the image part - kind of similar to what a high resolution crt do.

Is something like that possible on MiSTer? Maybe with the new polyphase filters and shadow masks.

**Comment by birdybro** [comment]
Here's an example of the effect. I'm pretty sure just using Bright Scanlines does this.

![image](https://user-images.githubusercontent.com/16388068/148886756-bb807557-2f64-4eb6-a654-1c03aa5d1bcb.png)

**Comment by darkworon** [comment]
Yes, you seems to be right - it works, but the intensity of this is less configurable and a little less pronounced so maybe just more brighter scanline filter (130, 140, etc.) would do the same job.

For example - mister (with Scan_Br_125_00) vs analogue super nt:

![IMG_1277](https://user-images.githubusercontent.com/192843/148915142-7c43ecfc-e212-4558-8702-789d2d8f05cd.jpeg)
![IMG_1275](https://user-images.githubusercontent.com/192843/148915183-a82771bf-8c80-4429-adc7-a4e9f92725de.jpeg)

**Comment by sorgelig** [comment]
if you don't look at crop with magnifying glass then what such hybrid scanlines doing is making dark colors more darker. You can simulate it pretty much close by using normal scanlines with special gamma correction.

**Comment by darkworon** [comment]
Алексей, спасибо большое) я понимаю смысл сканлайнов, просто хотелось разобраться в доступных возможностях кастомизации)

**Comment by sorgelig** [comment]
While standalone scalers may have more functions due to whole FPGA available for only scaling, MiSTer's scaler is just one part of framework. More resources used by framework means less resources left for cores. Especially 2 big cores in development PSX and Saturn occupying almost the whole FPGA. So it's more wise to not occupy too much resources by framework. When these cores will be released, then it will be known how much resources left and then some features might be re-considered.
