### ISSUE TITLE
Development guide

### ISSUE THREAD

**Issue by victorcoder** [MiSTer-devel/Main_MiSTer#53]
Hi @sorgelig, I've been learning on how to compile and run SoCs apps for our MiSTer, I started with the Main MiSTer.

I'm a Mac user I soon noticed is not a good platform to develop for this kind of boards, most of the frameworks are only available for Win and Linux. No problem with that I can use a VM to develop.

What I noticed is that for example Main_MiSTer you are using Windows and Visual Studio for development but I will want to provide a guide for developing on Win and Linux, this will bring much opportunity to other users to start developing for the platform and I think this is always good.

I managed to get a quite good and capable dev environment using Quartus Prime and ARM DS with eclipse.

I would like to know, if you are interested, if I can create a README in the project or a Wiki page describing how to setup and start developing for mister from scratch.

What do you think?

**Comment by sorgelig** [comment]
Guides are always good. That's why Wiki exists. So you a free to write the guide there.
Main_MiSTer is compiled in gcc. It has proper Makefile. So in Linux with ARM GCC toolchain you can compile it right away. VisualStudio i use just for writing the code and syntax highlighting with traveling (which goes through all linux system sources when it properly included). It also automatically uses gcc in msys shel to compile the code. IMHO it's the best IDE i ever used. VS just for convenience and it's not required. Any text editor can be used for developing.
I know Eclipse - i've used it a lot when i developed for Android. Pretty much heavy and slow IDE although rich enough. Probably on non-Windows OS it's a good alternative.

**Comment by sorgelig** [comment]
it seems abandoned..

**Comment by CronoMaxwell** [comment]
can we use VS Code to write the code then push it to the VS IDE?

**Comment by victorcoder** [comment]
Yup, sorry, I didn't found time to allocate :(

**Comment by sorgelig** [comment]
> 
> 
> can we use VS Code to write the code then push it to the VS IDE?

i'm not sure what you mean. .sln file is to load the project into VS2017 IDE.
