### ISSUE TITLE
ESD protection

### ISSUE THREAD

**Issue by zerohimself** [MiSTer-devel/Main_MiSTer#57]
So, last week I damaged the FPGA on my DE10 board by accidently supplying a ESD shock to the button housing of the OSD menu on the IO board. The shock killed both GPIO pins for the OSD and USER buttons. I was using the IO board 5.5

I'm wonder if there is any protection that we can put in, maybe a diode somewhere?
Maybe this is a user issue, as we take that risk by using a bare PCB not in a case, but I figured I should report the issue and at least make a suggestion for someone who is more knowledgeable than me.

**Comment by sorgelig** [comment]
I don't think it's possible to do anything against it. If you got high static charge on your body due to specific wear or something on surface where you walk, then discharge will be too high to protect 3V electronic device.
You need the case where buttons will be protected by thick plastic. 
It's better to find the source of charge, put some grounded line which you will touch before touching electronic devices.

**Comment by alfishe** [comment]
ESD protection was invented for a reason. TVS diodes can dissipate electrostatic charge if positioned properly. The question is whether it''s worth efforts and extra cost. http://www.ti.com/product/ESDS302

**Comment by sorgelig** [comment]
it won't prevent damage if other parts of PCB will be touched.
