### ISSUE TITLE
MGL and Turbo Grafx 16 / CD

### ISSUE THREAD

**Issue by Paradox** [MiSTer-devel/Main_MiSTer#588]
Since both use the same core, the default mapping for both is turbogrfx16, but, even in the core, when you attempt to open a CD, it uses the default path of turbografx16-cd, allowing you to keep chd files on a separate storage device, but, this doesn't work, since mgl wants them to be in the original default directory... This can be overridden by using the ../../../ trick, but, it shouldn't be needed, it should have it's own label turbografx16-cd...

**Comment by sorgelig** [comment]
i see. i will check it.

**Comment by sorgelig** [comment]
should be fixed in my latest commit.

**Comment by Paradox** [comment]
You forgot chd

**Comment by sorgelig** [comment]
nope. chd should work too.

**Comment by Paradox** [comment]
> nope. chd should work too.

no, it doesn't, I tested it.

**Comment by Paradox** [comment]
I didn't realize this change wasn't in the latest release, and I needed to use unstable nightly to use it, I apologize, it is working as expected.

**Comment by sorgelig** [comment]
Atari800 and Atari5200 weren't one device. There where 2 devices not compatible to each other. Atari7800 was originally made to play Atari2600 carts.

**Comment by birdybro** [comment]
@Paradox It was easier to add support for this for TGFX16-CD for one key reason, there is already a definition for tgfx16-cd because it requires a whole set of support code to get CD handling to work:

https://github.com/MiSTer-devel/Main_MiSTer/blob/df89fa675f636b779bb2c8f96f71ab8dc7cf8cc0/support/pcecd/pcecd.h#L141

https://github.com/MiSTer-devel/Main_MiSTer/blob/df89fa675f636b779bb2c8f96f71ab8dc7cf8cc0/support/pcecd/pcecd.cpp#L228

There is no equivalent special handling of Atari7800 having an optional folder for Atari2600 based solely upon a file extension of `.a26`.

Even the distribution doesn't create that folder anymore because the folders are based upon the internal core's name. If users are placing GBC games into a separate folder outside of GameBoy, then they are using it in a way it's not designed to be used.

You should advise the users of your script to place Atari 2600 games, and GameBoy Color games, and Game Gear games in that core's appropriate default folder. e.g.:

![image](https://user-images.githubusercontent.com/16388068/170170273-d644bdcc-24c2-4722-a5d7-818f97165ed4.png)

![image](https://user-images.githubusercontent.com/16388068/170170304-c5f3323b-a0d3-4f6b-b10d-8db8ec3527c3.png)

![image](https://user-images.githubusercontent.com/16388068/170170348-30aef90c-b3c8-4d32-81f9-bfa935409b3a.png)

**Comment by sorgelig** [comment]
There is no reason to split into different folders. Supported formats and additional systems are written in ReadMe for specific core.
CD folder for TGFX16 is different because of large space required for it and it's easier to move it to external storage.
