### ISSUE TITLE
Bring PCXT_MiSTer repo to mister-devel?

### ISSUE THREAD

**Issue by jsmolina** [MiSTer-devel/Main_MiSTer#648]
This is a very interesting development, as many XT games (and apps) won't work on ao486. 
Examples of not working games on ao486 are: Prohibition, Tapper, Popcorn.

https://github.com/spark2k06/PCXT_MiSTer

The core is just missing a simpler way of loading FDD or HDD, as now it is using loopback serial interface.

**Comment by sorgelig** [comment]
Looking at TODO list, it's too early to talk about it. 
Some time ago i wanted to port Next186, but that core require direct SD card access. It's possible to use VHD as virtual SD card, but handling this core will be too difficult as you have to put all disk images inside VHD. 
So, yes, basically FDD and IDE must be implemented properly so images will be able to mount directly without VHD container.

**Comment by spark2k06** [comment]
In this case nothing related to Next186 is used anymore, it is a combination of the MCL86, Graphics Gremlin and KFPC-XT projects as chipset, still with issues to be solved by its author, @kitune-san. 

However, I have implemented a partial and temporary solution in beta 1.0, so that it can be used by more users and receive feedback, and it is nothing else than the internal UART loading of the MiSTer, with the help of serdrive running on the Linux side via a script.

There is still the challenge of providing 8-bit IDE support, but this has nothing to do with the complexity of the Next186, thanks to KFPC-XT, we have at our disposal a bus much easier to understand, even so, I for my part without some clear examples or implementation already developed, I find it difficult to provide IDE support ... and this is the point where the project is.

**Comment by sorgelig** [comment]
The way it mounts disk now is completely different than user may expect. It's not ready for wide audience. It also better to keep it away from downloader so normal users won't get strange core which they will complain about. I don't see a problem to do a beta testing on MiSTer forum providing a link to repository.
When it will get usual way to mount through OSD file browser then there will be a time to move to MiSTer-devel and normal release.

**Comment by spark2k06** [comment]
Yes, there is already a thread related to this core in the forum, and it is already starting to be tested by users from this latest beta:

https://misterfpga.org/viewtopic.php?p=54369#p54369

**Comment by jsmolina** [comment]
@sorgelig could you please give a tip on how floppy/HD access could be added to this core? Now it's pretty awesome and it's missing the 'productization'.
Lof of thanks.

**Comment by spark2k06** [comment]
I prefer the use of original BIOS to custom ones, for many reasons. Especially, maintenance and support of model-specific video modes, like Tandy.

**Comment by spark2k06** [comment]
Jul 14, 2022 11:50 am

The IDE implementation must be compatible with XTIDE Universal BIOS, which is the one currently in use. It is a solid and mature BIOS for this purpose.

**Comment by sorgelig** [comment]
It's up to you. I just gave advice of probably simpler implementation for disk i/o.

As for IDE/FDC - probably it's worth to check which commands are used in BIOS and implement only that subset of commands in IDE and FDC. MiSTer already has IDE implementation available for cores. May be it's already enough, or just add missing commands if any.

**Comment by sorgelig** [comment]
I didn't look into code of core. So i cannot answer for specific question. 
Yes, my idea is to use custom BIOS code to mimic IDE/FDC read/write operation using sd_* signals. HDL code can add some wrapper for easier access, like sector transfer to a specific PC_XT memory address directly.
