### ISSUE TITLE
goodmerge support (7zip)

### ISSUE THREAD

**Issue by skunx99** [MiSTer-devel/Main_MiSTer#66]
Since the mister supports zip, would it be possible to add goodmerge support?

1) support for 7z (if not already possible)
2) support for reading the lan codes (only show US) if [u] is in the file name.
3) sort 7zip files with [!] (verified roms) first.

There are many other cool things about the 7z collection but those are the big ones. If you can already open the 7z files, the rest is easy enough just to sort or auto run files with [!].  I have a lot of info on how goodmerge works if needed.

**Comment by sorgelig** [comment]
7z is not supported.
Sorting huge folders (which is the case in most such archives) is very lengthy operation. Doing additional filter where *EVERY* name must be additionally processed to find specific patters will make sorting very long. And since it's not a PC with a lot of memory and caches, here you can't re-visit the folder and have quicker opening. Every enter will have the same sorting time, so every enter press will give you long processing time. 

I will keep it in mind.

**Comment by skunx99** [comment]
Not sure this really helps the points you addressed but it would only really be fore those that use samba and a network based rom collection. In other words a person with this set, would want to keep that set on the main drive and just access it via samba. Thx for the consideration.

**Comment by sorgelig** [comment]
Network access only increase the access time. So it will be even worse.
