### ISSUE TITLE
Link scripts in the main menu

### ISSUE THREAD

**Issue by wizzomafizzo** [MiSTer-devel/Main_MiSTer#664]
It would be nice to have the option to link scripts directly in the main menu rather than them being only accessible from the separate Scripts menu. Some scripts are used frequently and add functionality to the menu, and it would make sense to git them some context in the menu itself.

An additional option that would be useful is to be able to mark a linked script as being run in the background, so they'd be run immediately without switching to the console. This is useful for actions that don't benefit from any output and would be huge for better integrating them in the menu.

Some ideas for this working:
- Symlink from /media/fat/Scripts/stuff.sh to "/media/fat/My Script.sh" would show as "My Script" in the menu root
- Symlink from /media/fat/Scripts/stuff.sh to "/media/fat/My Script.background.sh" would show in menu root but not switch to the console on launch
- Maybe not a good fit but perhaps .mgl files could be used for this purpose rather than symlinks?

**Comment by sorgelig** [comment]
Scripts are not made for normal use. They are quirks to fix some problems originally requiring console login. It will stay that way. They SHOULD be inconvenient to distract of using them.

**Comment by wizzomafizzo** [comment]
Let's say I had a pull request ready right now, up to your coding standards, which implemented a system for managing favourite game shortcuts and searching your games collection for the menu binary. Would you accept this pull request or would you reject it on principle that mister does not need these features?

**Comment by sorgelig** [comment]
Considering that some cores may have thousands of games and some/all can be inside the zip files. Some cores may have games on SD card, some cores may have it on USB or even on network drive. Considering all these variables i don't see such function as reliable feature. 
I'm also user of MiSTer and i had no such need. If i want to play specific game, then i have some info what is that, which system it belongs. So it's not a problem to launch required core and then browse it. Searching by typing from keyboard also implemented.
CPU on MiSTer is not that fast to add such feature.

**Comment by wizzomafizzo** [comment]
You are right, I have made these things work but with a lot of trade offs. It is "good enough" not polished. But I think you have answered my question, you say at least partially you don't like the feature because you would not use it. The thing is I **would** use it and so would many others. Perhaps mister would not be what it is today without your strong guidance, but it is still very frustrating to have you deny this stuff outright because "you don't need it"

I just have one more question and I'll get out of your hair ok. I feel I'm at a junction after this conversation. Right now my scripts rely on things like: mgl file allowing relative paths, mister shipping with binaries to play audio, the Scripts menu existing. Are these staying in place? If you removed them, would you accommodate workarounds for similar functionality?

I am ok to keep working in the background, bolting on this stuff that you don't really want in mister. But I don't want to do it anymore if you actively disapprove of such things and wouldn't have a problem crippling them if you though it was necessary.

**Comment by sorgelig** [comment]
> but it is still very frustrating to have you deny this stuff outright because "you don't need it"

i'm sorry if it sounds like this. There of course several ways to organize the games. There are always pros and cons. In your case, it requires a lot of preparation before it will act as you described. Or user has to relay on pack with pre-made folder structures filled with links depending on specific rom sets. Do you think MiSTer should be advertised as "Download this pack with pirated ROMs and you are set"? The way i develop MiSTer, it doesn't require preparation. And it doesn't require specific folder structure. My use case: i get the ROM, place into games/<core> folder and it works right away. It doesn't need to add thousands of games at once, or keep the thousands of broken links (since not roms are present).
MGS is still a quirk and don't expect it fully replace a normal use.


> Right now my scripts rely on things like: mgl file allowing relative paths, mister shipping with binaries to play audio, the Scripts menu existing. Are these staying in place? If you removed them, would you accommodate workarounds for similar functionality?

Binaries to play audio included to use MiSTer as a subset of computer where you can login to Linux locally and in file manager (mc) you can directly press or select and press <enter> the files you want to play if you are boring. Or may be you want to check something. 
Background playback in menu core is not intended feature. If it works OK for you, then you may use it. Some people have screen glitches in Menu core while transferring files over network. So there is no plans to add background CPU/Memory load such background audio playback. 
Probably MiSTer can be used in many other scenarios, but there is no plans to make a generic computer from MISTer.

**Comment by wizzomafizzo** [comment]
Thank you Sorg, I appreciate you taking the time to elaborate your point of view for me. It's not the answer I wanted to hear, but I understand it better and can accept it

That said, surely you appreciate that there is an appetite for extending mister in ways you have not intended, and that these things have merit to other people. If you ever want to make a change that may impact existing features, please consider leaving an opening so functionality can be restored for those that do want it. It doesn't need to be some fancy plug-in framework, just something to work with, that won't impact users who want to keep it simple
