### ISSUE TITLE
[Feature request] Larger menu

### ISSUE THREAD

**Issue by arromdee** [MiSTer-devel/Main_MiSTer#673]
The menu isn't even 40x24 and if you're viewing it on any sort of modern display device, contains a ludicrously small amount of visible text.  I'm sure that some people are on CRTs and need this kind of menu, but could it at least be made larger with smaller text as an option?

**Comment by sorgelig** [comment]
Larger menu will require more precious resources taking it away from cores. Also it's max size possible in some resolutions in some cores.

**Comment by jotego** [comment]
Changing to a character-based menu instead of pixel based could make it larger for the same memory size. It would require several changes:

- Design new osd module in template
- New firmware to support this OSD
- Provide some backwards compatibility on firmware by detecting the type of OSD connected, so cores don't need recompiling
- The firmware could adjust the size of the OSD based on the active video pixels, so small geometries would work too

It's kind of a big change, so if the decision is not go this road, I suggest to close this issue as "won't do"

**Comment by sorgelig** [comment]
No problem to close. Just some time later the same "issue" will be opened :)
