### ISSUE TITLE
Skipping up/down/left/right definitions for spinners

### ISSUE THREAD

**Issue by jotego** [MiSTer-devel/Main_MiSTer#775]
When mapping the buttons of a spinner device, it will ask you first about the four directions: up, down, left, right. You cannot skip the definition of those. That forces you to use four device buttons before you get to the point of defining the actual core buttons. For the core itself you usually want at least three buttons: fire, coin and 1P start. Four plus three makes seven. I think there aren't many spinners around with seven buttons. The one in the image has six, for instance.

Could we have a way to skip definitions for directions? Either by pressing a key during the definition or maybe by having some attribute in the MRA for it, like `directions="false"`?

```
    <buttons directions="false" names="Shoot,-,-,Start,Coin,Core credits" default="Y,X,B,Start,Select,-" count="1"/>
```

![imagen](https://user-images.githubusercontent.com/1863036/235337216-0ea29737-2d33-4874-bc15-c06811327698.png)

**Comment by sorgelig** [comment]
MiSTer doesn't have such class of input devices because it cannot be used to navigate OSD and cannot be used to play almost all cores because basic directional buttons are required.
MiSTer supports either Game controller with integrated spinner/paddle OR separate spinner/paddle with single button.
Is second option such spinner/paddle will be overlaid on gamepad, so both spinner and gamepad will work as a common input device. This is the best i could make.

**Comment by sorgelig** [comment]
I've tried to explain the manufacturer, such device is invalid. It cannot be a normal controller. Unfortunately he let it go anyway.
It look fancy and cool, but it's not full controller to use it independently.
May be this device should include DB9 input, so Atari controller could be connected and used at the same time.

**Comment by jotego** [comment]
It makes sense. I understand it now. Thanks.
